name: PR for Prod EU branch
on:
  push:
    branches:
      - test_1
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: test_1
          target_branch: test_2
          title: My pull request
          body: "**Automated pull request**"
          reviewer: Dishant18
          assignee: Dishant18
          get_diff: true
          allow_no_diff: false